name: Publish at gh-pages

on:
  push:
    paths:
      - '.github/workflows/publish.yml'
      - 'src/*'
      - 'src/*/*'
      - 'src/*/*/*'
      - 'src/*/*/*/*'
      - 'static/*'

jobs:
  docs-build-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master

    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: 12.x

    - name: Build
      env:
        FOLDER: fuse-calc
      run: npm i && npm run gh-export

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v2
      env:
        ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: ./__sapper__/export/fuse-calc